spring.application.name=order_service

server.port=8081

user-service.base-url=http://localhost:8080

payment-service.base-url=http://localhost:8083

# Retry configuration
resilience4j.retry.instances.paymentService.max-attempts=3
resilience4j.retry.instances.paymentService.wait-duration=1s